const styles = () => ({
  avatar: {
    borderRadius: '50%',
    // border: '2px solid rgba(255,255,255,0.9)',
    boxSizing: 'border-box',
    width: 66,
    height: 66,
    marginTop: 37,
  },
  title: {
    color: '#fff',
    fontSize: 16,
    opacity: 0.9,
    lineHeight: '19px',
    fontFamily: 'Helvetica',
  },
  position: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 14,
    lineHeight: '17px',
    fontFamily: 'Helvetica',
  },
  address: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    lineHeight: '14px',
    fontFamily: 'Helvetica',
    fontWeight: 300,
  },
  button: {
    boxSizing: 'border-box',
    height: 23,
    width: 76,
    marginBottom: 30,
    border: '1px solid #FFFFFF',
    opacity: 0.9,
    borderRadius: 8,
    backgroundColor: 'transparent',
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    lineHeight: '14px',
    fontFamily: 'Helvetica',
    cursor: 'pointer',
  },
  skillList: {
    padding: 28,
    display: 'flex',
    flexFlow: 'row wrap',
    alignContent: 'left',
    justifyContent: 'left',
  },
  skillChip: {
    padding: '5px 10px',
    width: 'auto',
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.5)',
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: '17px',
    fontFamily: 'Helvetica',
    margin: 4,
    // cursor: 'pointer',
  },
  linkList: {
    display: 'flex',
    flexDirection: 'column',
  },
  link: {
    display: 'flex',
    alignItems: 'center',
    padding: '15px 26px',
    textAlign: 'left',
    color: '#FFFFFF',
    fontSize: 16,
    lineHeight: '19px',
    fontFamily: 'Helvetica',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    textDecoration: 'none',
  },
  icon: {
    paddingRight: 10,
  },
});

export default styles;
