const styles = () => ({
  title: {
    color: '#3F4E5D',
    opacity: 0.9,
    fontSize: 14,
    fontFamily: 'Helvetica',
    fontWeight: 'bold',
    lineHeight: '17px',
    paddingTop: 35,
    paddingLeft: 24,
  },
  submitBtn: {
    backgroundColor: '#1976D2',
    border: 'none',
    borderRadius: 4,
    textDecoration: 'none',
    padding: '12px 32px',
    opacity: 0.9,
    color: '#FFFFFF',
    fontFamily: 'Helvetica',
    fontSize: 14,
    lineHeight: '18px',
    display: 'inline-block',
    marginTop: 14,
    cursor: 'pointer',
  },
  cancelBtn: {
    backgroundColor: 'grey',
    border: 'none',
    borderRadius: 4,
    textDecoration: 'none',
    padding: '12px 32px',
    opacity: 0.9,
    color: '#FFFFFF !important',
    fontFamily: 'Helvetica',
    fontSize: 14,
    lineHeight: '18px',
    display: 'inline-block',
    marginTop: 14,
  },
});

export default styles;
